server:
  port: 8091
spring:
    application:
        name: base
    datasource:
        url: jdbc:mysql://172.16.0.85:3306/base?characterEncoding=UTF-8
        username: base
        password: base123
        driver-class-name: com.mysql.jdbc.Driver
